Passo para verificar se o artefato foi baixado

diff --git a/.github/workflows/azure-webapps-dotnet-core.yml b/.github/workflows/azure-webapps-dotnet-core.yml
--- a/.github/workflows/azure-webapps-dotnet-core.yml
+++ b/.github/workflows/azure-webapps-dotnet-core.yml
@@ -60,12 +60,20 @@ jobs:
         with:
           name: .net-app
 
+      - name: Verify artifact download
+        run: |
+          ls -la -v 1 ${{ github.workspace }}/myapp
+          if [ $? -ne 0 ]; then
+            echo "Error: Artifact .net-app not found or corrupted."
+            exit 1
+          fi
+
       - name: List contents of the artifact directory
-        run: ls -la .net-app/
+        run: ls -la ${{ github.workspace }}/myapp
 
       - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v2
         with:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
-          package: .net-app
+          package: ${{ github.workspace }}/myapp
